- job:
    name: irc-meetings-tox-ical
    parent: openstack-tox
    description: |
      Run tests using tox with the ``ical`` environment.
    vars:
      tox_envlist: ical

- project:
    name: openstack-infra/irc-meetings
    check:
      jobs:
        - irc-meetings-tox-ical
    gate:
      jobs:
        - irc-meetings-tox-ical
