project:  Training-guides Team Meeting
meeting_id: training_guides
agenda_url: https://wiki.openstack.org/wiki/Meetings/training-guides
schedule:
  - time:       '1700'
    day:        Monday
    irc:        openstack-meeting
    frequency:  weekly
    start_date: 20160111
chair:  Matjaz Pancur (matjazp)
description:  >
  The training-guides team meets weekly on IRC.
