project:  Training-guides Team Meeting
schedule:
  - time:       '1700'
    day:        Monday
    irc:        openstack-meeting
    frequency:  weekly
chair:  sarob
description:  >
  The training-guides team meets weekly on Monday at 1700 UTC on
  #openstack-meeting.
